# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Parallels.Parallels
PackageVersion: 21.2.27429
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /qn
  SilentWithProgress: /passive
Installers:
- Architecture: x86
  InstallerUrl: https://download.parallels.com/ras/v21/21.2.2.27429/RASClient-21.2.27429.msi
  InstallerSha256: C042D669CCDEBB18D50DB6F2DF552881EFCDEA7B964A049A92D15A9D78D1B9E4
  ProductCode: '{5571C254-2480-4613-9217-C6CBB39BDC8F}'
  AppsAndFeaturesEntries:
  - DisplayName: Parallels Client
    Publisher: Parallels International GmbH
    DisplayVersion: 21.2.27429
    ProductCode: '{5571C254-2480-4613-9217-C6CBB39BDC8F}'
    UpgradeCode: '{BC596E15-94D4-4513-A475-C218664792D5}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Parallels\Client'
- Architecture: x64
  InstallerUrl: https://download.parallels.com/ras/v21/21.2.2.27429/RASClient-x64-21.2.27429.msi
  InstallerSha256: 3F082D0035CA127880AFEE82FCD67392343BAEA555A2EFBDCC4B427E11239F86
  ProductCode: '{9E1096D2-9002-43A2-8E90-DCF86713D510}'
  AppsAndFeaturesEntries:
  - DisplayName: Parallels Client 64-bit
    Publisher: Parallels International GmbH
    DisplayVersion: 21.2.27429
    ProductCode: '{9E1096D2-9002-43A2-8E90-DCF86713D510}'
    UpgradeCode: '{BC596E15-94D4-4513-A475-C218664792D5}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Parallels\Client'
- Architecture: arm64
  InstallerUrl: https://download.parallels.com/ras/v21/21.2.2.27429/RASClient-ARM64-21.2.27429.msi
  InstallerSha256: 2D6B27D2E81C2D8C961241732A957B24086B9DF6013EEAC7354438C9B2577FFC
  ProductCode: '{CC97ABEC-A990-4B42-A086-D0D109FCE46F}'
  AppsAndFeaturesEntries:
  - DisplayName: Parallels Client ARM64
    Publisher: Parallels International GmbH
    DisplayVersion: 21.2.27429
    ProductCode: '{CC97ABEC-A990-4B42-A086-D0D109FCE46F}'
    UpgradeCode: '{BC596E15-94D4-4513-A475-C218664792D5}'
  InstallationMetadata:
    DefaultInstallLocation: Program Files\Parallels\Client
ManifestType: installer
ManifestVersion: 1.12.0
